name: CI
on:
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
      - '!master'
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
      - name: Install deps
        run: npm ci
      - name: Lint affected
        run: npx nx affected -t=lint --base=origin/master
      - name: Test affected
        run: npx nx affected -t=test --base=origin/master --configuration=ci
      - name: Build affected
        run: npx nx affected -t=build --base=origin/master
