name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./backroad-example.Dockerfile
          platforms: linux/arm64
          tags: backroad-example:latest
          outputs: type=docker,dest=/tmp/backroad-example.tar
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - run: ls -la /tmp
      - run: whoami
      - name: use ssh agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SUDOMAKES_KEY }}
      - name: do ssh
        env:
          HOST: ${{ secrets.SUDOMAKES_HOSTNAME }}
          USER: ${{ secrets.SUDOMAKES_USER }}
          PORT: ${{ secrets.SUDOMAKES_PORT }}
        run: |
          scp -o StrictHostKeyChecking=no -P $PORT /tmp/backroad-example.tar $USER@$HOST:/home/$USER
          ssh -o StrictHostKeyChecking=no -p $PORT $USER@$HOST 'ls -la /tmp/ && docker load  --input /home/$USER/backroad-example.tar'
